### ISSUE TITLE
[Admin] Overtext

### ISSUE THREAD

**Issue by firiousity** [iskandar1023/cbte#12]
in making new account or edit

![image](https://user-images.githubusercontent.com/21122424/34022797-0243abc0-e174-11e7-9a67-9ff8f62a4357.png)

**Comment by iskandar1023** [comment]
Coba lagi

**Comment by iskandar1023** [comment]
Eh ngga

**Comment by iskandar1023** [comment]
Fixed with https://github.com/iskandar1023/cbte/commit/e4c2cdb39092cbc1627fdcf85eab86b8f6bb1526
