### ISSUE TITLE
[Dosen] Buat Soal

### ISSUE THREAD

**Issue by firiousity** [iskandar1023/cbte#16]
If checked and choose cancel, button save and tinjau cant be clicked

![image](https://user-images.githubusercontent.com/21122424/34240908-3186a548-e644-11e7-86c1-b8324d534de2.png)

**Comment by iskandar1023** [comment]
Will "fix" someday by converting all dialogs to modal

**Comment by firiousity** [comment]
why not sooner tho? or is it more complicated things to fix despite the simple looks?
