### ISSUE TITLE
[Suggestion] [Dosen] Tip Bobot

### ISSUE THREAD

**Issue by firiousity** [iskandar1023/cbte#23]
Mungkin kasih keterangan jumlah maksimal bobot? In case ada dosen yang terbiasa dengan rentang 0-10 poin

![image](https://user-images.githubusercontent.com/21122424/34299452-8ea272cc-e755-11e7-9238-e5e6dbd60399.png)

**Comment by kelikisc** [comment]
sekiranya gue ajasih dosen udh terbiasa ko kalo di tingkat kuliah total nilai 100, yg sampe 10 di sd doang paling tp adek gue juga udah total 100

**Comment by firiousity** [comment]
awright
