### ISSUE TITLE
[Dosen] Nilai Ujian Perserta

### ISSUE THREAD

**Issue by firiousity** [iskandar1023/cbte#7]
-Edit nilai tidak keluar, tetap nilai awal

**Comment by iskandar1023** [comment]
Pls explen thx

**Comment by firiousity** [comment]
dosen udah nilai (ex:90) trus ada tombol edit. Kalo diubah nilainya yg akan ditampilkan tetap nilai awal, tapi nilai hasil editnya tetap kesimpan @iskandar1023
