### ISSUE TITLE
[Mahasiswa] Lihat Nilai

### ISSUE THREAD

**Issue by firiousity** [iskandar1023/cbte#8]
Nilai jadi banyak hasil dari permasalahan di  #7

**Comment by iskandar1023** [comment]
Pls explen thx

**Comment by firiousity** [comment]
Nilai awal dan nilai hasil editan dari dosen akan muncul semua pada 1 tes yg sama.
For instance:
Hasil tes 1
- 90 (awal)
- 80 (edited)
- 85 (edited)
- ...(edited)

**Comment by iskandar1023** [comment]
Should be fixed with https://github.com/iskandar1023/cbte/commit/3fb014f799b384a0a47bd4ed14df5c9ce4e25246
Kindly reopen this issue if the problem still occurs.
